### ISSUE TITLE
spaces in links/markdown filenames

### ISSUE THREAD

**Issue by dcalacci** [jason6/vimwiki_md2html#1]
So I can't quite figure out if this is an issue with vimwiki or something that should be added in this script, but when the filename of an input markdown file has spaces in it (which is understandable considering creating links that have spaces in them is common), like: `/Users/username/vimwiki/hello world.md`, vimwiki passes the filename _with the spaces_...and with the current usage of argparse, the script understandably complains about not being able to find `/Users/username/vimwiki/hello`.  

So, is there a way to mess with argparse so it can handle spaces in the filenames (I don't know, but after  ~20 mins of looking around, i can't find an easy way in this context), or is this an issue to be brought up with the vimwiki folks to change the filepath that's passed to a custom wiki2html script so it's delimited with quotes?

**Comment by jason6** [comment]
This is a limitation of vimwiki.  As it currently stands, when Vimwiki2HTML is executed it outputs a command with positional arguments like:

 !/home/username/vimwiki/misaka_md2html.py 1 markdown md /home/husername/wiki_location/html /home/username/hello world.md /home/username/html/style.css

The only way for any normal parser to parse this is to determine each argument based on the space character between it and the next one.  

Vimwiki would need to output a quoted argument like "hello world.md" or change all the arguments to optional arguments like --outputfile=hello world.md --cssfile=style.css

Without this there is no way to know where one argument with an arbitrary number of spaces starts end and another one begins.
